"""
MLflow Artifact 管理工具

提供模型卡片、摘要等 artifact 的生成和记录功能。
"""

import mlflow
import json
import os
from pathlib import Path
from typing import Dict, Optional, Any
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def save_model_summary(
    model_info: Dict[str, Any],
    artifact_path: str = "model_summary.json",
) -> str:
    """
    保存模型架构摘要

    Args:
        model_info: 模型信息字典（包含架构、参数量、输入输出形状等）
        artifact_path: Artifact 路径

    Returns:
        本地临时文件路径
    """
    import tempfile

    # 创建临时文件
    temp_dir = tempfile.mkdtemp()
    temp_path = os.path.join(temp_dir, artifact_path)

    # 写入 JSON
    with open(temp_path, 'w') as f:
        json.dump(model_info, f, indent=2)

    # 记录到 MLflow
    mlflow.log_artifact(temp_path, artifact_path=os.path.dirname(artifact_path) or ".")

    logger.info(f"Saved model summary to {artifact_path}")
    return temp_path


def create_model_card(
    model_name: str,
    model_version: str,
    metrics: Dict[str, float],
    params: Dict[str, Any],
    dataset_info: Dict[str, Any],
    description: Optional[str] = None,
    limitations: Optional[str] = None,
    usage_example: Optional[str] = None,
    artifact_path: str = "model_card.md",
) -> str:
    """
    自动生成 Model Card

    Args:
        model_name: 模型名称
        model_version: 模型版本
        metrics: 评估指标字典
        params: 超参数字典
        dataset_info: 数据集信息
        description: 模型描述
        limitations: 模型局限性说明
        usage_example: 使用示例代码
        artifact_path: Artifact 路径

    Returns:
        本地临时文件路径
    """
    import tempfile

    # 构建 Model Card 内容
    card_content = f"""# Model Card: {model_name}

**Version**: {model_version}
**Date**: {datetime.now().strftime('%Y-%m-%d')}

## Model Description

{description or "PIU (Problematic Internet Use) risk classification model"}

## Intended Use

This model is designed to predict the severity of problematic internet use in children and adolescents based on:
- Demographic and behavioral tabular features
- Actigraphy (physical activity) sensor data

**Primary Use Case**: Research and clinical screening tool
**Out-of-Scope Use**: Not for diagnostic purposes without clinical validation

## Training Data

- **Dataset**: Child Mind Institute - Problematic Internet Use
- **Samples**: {dataset_info.get('n_samples', 'N/A')}
- **Features**: {dataset_info.get('n_features', 'N/A')}
- **Classes**: 4 (None, Mild, Moderate, Severe)
- **Split**: {dataset_info.get('split_strategy', 'Stratified Group K-Fold')}

## Model Architecture

**Type**: {params.get('model_type', 'N/A')}
**Framework**: {params.get('framework', 'PyTorch')}

### Hyperparameters

```json
{json.dumps({k: v for k, v in params.items() if k in ['hidden_dims', 'dropout', 'learning_rate', 'batch_size', 'epochs']}, indent=2)}
```

## Performance Metrics

**Primary Metric**: Quadratic Weighted Kappa (QWK)

| Metric | Value |
|--------|-------|
| QWK | {metrics.get('qwk', 0.0):.4f} |
| Macro-F1 | {metrics.get('macro_f1', 0.0):.4f} |
| Balanced Accuracy | {metrics.get('balanced_accuracy', 0.0):.4f} |
| Log Loss | {metrics.get('log_loss', 0.0):.4f} |

## Usage Example

```python
{usage_example or '''
import mlflow

# Load model
model = mlflow.pyfunc.load_model("models:/piu-risk@champion")

# Prepare input
input_data = {
    "age": 12,
    "bmi": 18.5,
    # ... other features
}

# Predict
prediction = model.predict(input_data)
print(f"Predicted class: {prediction}")
'''}
```

## Limitations

{limitations or '''
- Model trained on specific demographic distributions
- Actigraphy coverage: ~36% of labeled samples
- Performance may vary across different populations
- Not validated for clinical diagnosis
'''}

## Ethical Considerations

- **Privacy**: Model operates on de-identified data
- **Fairness**: Performance should be evaluated across demographic subgroups
- **Transparency**: All training code and metrics are tracked in MLflow

## License

MIT License (or specify your license)

## Citation

```bibtex
@misc{{piu-risk-model,
  title={{PIU Risk Classification Model}},
  author={{MLsystem Course Project}},
  year={{2026}},
  howpublished={{\\url{{https://github.com/your-repo}}}}
}}
```

## Contact

For questions or issues, please contact: [your-email]

---

*This model card was automatically generated by the MLflow utilities.*
"""

    # 创建临时文件
    temp_dir = tempfile.mkdtemp()
    temp_path = os.path.join(temp_dir, artifact_path)

    # 写入文件
    with open(temp_path, 'w') as f:
        f.write(card_content)

    # 记录到 MLflow
    mlflow.log_artifact(temp_path, artifact_path=os.path.dirname(artifact_path) or ".")

    logger.info(f"Created model card at {artifact_path}")
    return temp_path


def save_inference_script(
    model_name: str,
    feature_names: list,
    preprocessing_steps: Optional[str] = None,
    artifact_path: str = "inference.py",
) -> str:
    """
    生成最小推理脚本

    Args:
        model_name: 模型名称
        feature_names: 特征名称列表
        preprocessing_steps: 预处理步骤说明
        artifact_path: Artifact 路径

    Returns:
        本地临时文件路径
    """
    import tempfile

    inference_code = f'''"""
Minimal inference script for {model_name}

Usage:
    python inference.py --input sample_input.json --output predictions.json
"""

import mlflow
import pandas as pd
import numpy as np
import json
import argparse
from pathlib import Path


# Expected feature names (in order)
FEATURE_NAMES = {feature_names[:10]}  # First 10 shown


def load_model(model_uri: str = "models:/{model_name}@champion"):
    """Load the champion model from MLflow"""
    return mlflow.pyfunc.load_model(model_uri)


def preprocess(data: dict) -> pd.DataFrame:
    """
    Preprocess input data

    {preprocessing_steps or "Note: Add preprocessing logic here"}
    """
    df = pd.DataFrame([data])
    # Ensure correct column order
    # df = df[FEATURE_NAMES]
    return df


def predict(model, input_data: dict) -> dict:
    """
    Run inference on input data

    Args:
        model: Loaded MLflow model
        input_data: Dict of feature values

    Returns:
        Dict with prediction and probabilities
    """
    # Preprocess
    df = preprocess(input_data)

    # Predict
    prediction = model.predict(df)[0]

    # Get probabilities if available
    try:
        proba = model.predict_proba(df)[0]
        result = {{
            "prediction": int(prediction),
            "probabilities": proba.tolist(),
            "confidence": float(np.max(proba))
        }}
    except AttributeError:
        result = {{
            "prediction": int(prediction)
        }}

    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str, required=True, help="Input JSON file")
    parser.add_argument("--output", type=str, default="predictions.json", help="Output JSON file")
    parser.add_argument("--model-uri", type=str, default="models:/{model_name}@champion", help="MLflow model URI")
    args = parser.parse_args()

    # Load model
    print(f"Loading model from {{args.model_uri}}...")
    model = load_model(args.model_uri)

    # Load input
    with open(args.input, 'r') as f:
        input_data = json.load(f)

    # Predict
    print("Running inference...")
    result = predict(model, input_data)

    # Save output
    with open(args.output, 'w') as f:
        json.dump(result, f, indent=2)

    print(f"Predictions saved to {{args.output}}")
    print(f"Predicted class: {{result['prediction']}}")


if __name__ == "__main__":
    main()
'''

    # 创建临时文件
    temp_dir = tempfile.mkdtemp()
    temp_path = os.path.join(temp_dir, artifact_path)

    # 写入文件
    with open(temp_path, 'w') as f:
        f.write(inference_code)

    # 记录到 MLflow
    mlflow.log_artifact(temp_path, artifact_path=os.path.dirname(artifact_path) or ".")

    logger.info(f"Saved inference script to {artifact_path}")
    return temp_path


def save_input_example(
    example_data: Dict[str, Any],
    artifact_path: str = "sample_input.json",
) -> str:
    """
    保存示例输入

    Args:
        example_data: 示例输入数据
        artifact_path: Artifact 路径

    Returns:
        本地临时文件路径
    """
    import tempfile

    # 创建临时文件
    temp_dir = tempfile.mkdtemp()
    temp_path = os.path.join(temp_dir, artifact_path)

    # 写入 JSON
    with open(temp_path, 'w') as f:
        json.dump(example_data, f, indent=2)

    # 记录到 MLflow
    mlflow.log_artifact(temp_path, artifact_path=os.path.dirname(artifact_path) or ".")

    logger.info(f"Saved input example to {artifact_path}")
    return temp_path
